### PR TITLE
Fix CVE issues for WFTOP : Junit, guava, java-lib and httpasyncclient

### PR DESCRIPTION
**Pull request by yogeshprasad**
Fix CVE issues for JUnit, guava, java-lib and httpasyncclient.

List of Jira tickets  
https://jira.eng.vmware.com/browse/INT-1627
https://jira.eng.vmware.com/browse/INT-1628
https://jira.eng.vmware.com/browse/MONIT-29220
https://jira.eng.vmware.com/browse/MONIT-29221

### CODE REVIEW

**Comment by yogeshprasad** [comment]
@srinivas-kandula please have a look

**Review by gangadharaswamy — APPROVED** [review]

**Comment by srinivas-kandula** [comment]
@yogeshprasad, What is the MONIT ticket for this and what are recommended versions?

**Comment by yogeshprasad** [comment]
> @yogeshprasad, What is the MONIT ticket for this and what are recommended versions?

https://jira.eng.vmware.com/browse/INT-1627
https://jira.eng.vmware.com/browse/INT-1628
I upgraded to the latest version

**Review by srinivas-kandula — APPROVED** [review]
LGTM

**Pull request merged**
